#!/bin/sh

. /lib/functions.sh

[ "$DEVICE" == "lo" ] && exit 0

case "$ACTION" in
  ifup)
    if [ "$DEVICE" == "br-lan" ]; then
      /etc/init.d/cifs restart
    fi
    ;;
  ifdown)
    if [ "$DEVICE" == "br-lan" ]; then 
      /etc/init.d/cifs stop
    fi
    ;;
esac
