#!/bin/sh /etc/rc.common

START=99
STOP=15

start() {
echo start

/sbin/sysctl -w net.ipv6.conf.all.disable_ipv6=1
/sbin/sysctl -w net.ipv6.conf.default.disable_ipv6=1
/sbin/sysctl -w net.ipv6.conf.lo.disable_ipv6=1
/sbin/sysctl -w net.ipv6.conf.eth0.disable_ipv6=1
/sbin/sysctl -w net.ipv6.conf.default.forwarding=0
/sbin/sysctl -w net.ipv6.conf.all.forwarding=0
}

stop() {
echo stop

}
